### ISSUE TITLE
unintended replacements in remove_needless_u_specifier example

### ISSUE THREAD

**Issue by acdha** [Yelp/undebt#10]
I gave undebt a try using remove_needless_u_specifier.py and noticed some instances where it replaced more than expected when a string ended with a `u` character:

```diff
     try:
         subprocess.check_call(('mysql',
-                               '-u', 'test_user',
+                               '-', 'test_user',
…)
```

```diff
 TITLE_LABELS = {
     "en": ("Subject", ),
-    "ru": ("Тема", ),
+    "r": ("Тема", ),
     "fr": ("Objet", "Sujet"),
…
```

**Comment by ajm188** [comment]
Yes, it seems like the grammar in `remove_needless_u_specifier` should be made to only look for unquoted `u`s.
