### ISSUE TITLE
Dry run option should have variant to show diff

### ISSUE THREAD

**Issue by Daenyth** [Yelp/undebt#18]
From https://github.com/Yelp/undebt/pull/5#issuecomment-242389456

The dry run option should have a variant command that will print a standard unified diff to stdout instead of printing the new file version.

For a test case, we should be able to `assert dry-run-stdout == (dry-run-with-diff-stdout-piped-to-patch)`

**Comment by asottile** [comment]
For patch there's an edgecase when a file doesn't end with a newline (be sure to test that too!)

Here's how I tested this: https://github.com/asottile/reorder_python_imports/blob/b022734351abe44d0b05a71a4fa1175287c59b49/tests/main_test.py#L453-L482

**Comment by ajm188** [comment]
@Daenyth Hi! Sorry for the (massive) delay

I'm not really sold on this idea, namely because I can do `diff my-file $(undebt --dry-run -p my.pattern my-file)`.

**Comment by ajm188** [comment]
I've closed, but if you can make a case for why undebt should add this to the CLI, I'm happy to repoen and discuss.

**Comment by Daenyth** [comment]
I think given the workaround you posted it's not critical to add, especially if you want to keep a very slim interface. It would be convenient, but not totally necessary.
