### ISSUE TITLE
How can I match only standalone NAMEs?

### ISSUE THREAD

**Issue by yoloseem** [Yelp/undebt#19]
I expected that DOTTED_NAME will matched only standalone identifiers (identifiers that start a new expression) but it also matches trailing ones.

For instance I wrote a recipe to apply some patterns like `util.asbool(request.form.get('flag', False))` => `request.form.get('flag', False, type=util.asbool)` and it unexpectedly made a change like below:
```python
- a = session.query(Model).get(request.form.get('id'))
+ a = session.query(Model).request.form.get('id', type=get)
```

(By the way, this tool is awesome! 👍 🍰 👍  Thanks.)

**Comment by evhub** [comment]
@yoloseem You want `ATOM` not `DOTTED_NAME`. The problem is that `query(Model)` is not valid in a `DOTTED_NAME`, because it contains a function call. `ATOM` will match function calls and indexing as well as attribute access. Tell me whether that fixes your problem or not. And thanks!

**Comment by yoloseem** [comment]
I expected that the attached case wouldn't be affected if all goes right, since it's not a casting function. However as you mentioned ATOM fixed all problems at least in not breaking code. There's no silver bullet, I learned once again. 😭😭😭 Thanks a lot!
