### ISSUE TITLE
Adding a 'stdlib' of anti-patterns fixes

### ISSUE THREAD

**Issue by lwm** [Yelp/undebt#21]
Something that [quantified code](https://www.quantifiedcode.com/) (will shutdown in october) was trying to achieve, was a tool that could detect bad python code and rewrite it for you. Writing patterns involved using their DSL but with `undebt`, we can write them in python!

They had a rather sizeable list of anti-patterns:
- https://www.quantifiedcode.com/knowledge-base/

Do you imagine the `undebt` repository as a place for a 'stdlib' of python code fixups that it could run automatically on a code base, based on the above anti-patterns?  We could start to port the anti-patterns into grammar definitions.

**Comment by evhub** [comment]
@lwm Yeah! That sounds like exactly the sort of thing that undebt would be great at. You're welcome to submit a PR for adding any of the above patterns to [`undebt/examples`](https://github.com/evhub/undebt/tree/master/undebt/examples) as long as you also include tests in [`tests/examples`](https://github.com/evhub/undebt/tree/master/tests/examples).

**Comment by lwm** [comment]
@evhub Great! I'll start to play with them and add as I go. If you don't mind, I'll keep this issue open to track my progress and also for visibility for anyone who wants to join.

**Comment by evhub** [comment]
@lwm Sounds good!

**Comment by thundergolfer** [comment]
@lwm I had this same thought on seeing this release. Have you started on your idea?

**Comment by lwm** [comment]
@thundergolfer
Not yet. Something coming soon. Please feel free to start as well and we can sync along the way! The more the merrier!

**Comment by lwm** [comment]
Oh, another idea related to this, once there are more patterns.

We could [write a new linter](https://pylama.readthedocs.io/en/latest/#writing-a-linter) for [pylama](https://pylama.readthedocs.io/en/latest/#), which plugs directly into [pytest](http://doc.pytest.org/en/latest/). 

Then you'd get `py.test --undebt` and something cool would happen.

**Comment by ajm188** [comment]
@lwm good idea!

I'm going to plug Yelp a little here (not biased at all 😛), but #40 allows `undebt` to be used as a [`pre-commit` hook](https://github.com/pre-commit/pre-commit) (also a yelp project). So you can run `undebt` to prevent code smells and the like from ever being committed! (which I think you'll agree qualifies as "something cool happening" :) )
