### ISSUE TITLE
Example test case for Swift 2.2 to Swift 3.0

### ISSUE THREAD

**Issue by steve21124** [Yelp/undebt#26]
first question, is this undebt only work for python code? if it work for other language that is "pyparsing grammar object" 

for example in current swift 2.2, it is written like below
if let x = y, a = b where a == x {

how to use "undebt" to parse above line to below line?
if let x = y, let a = b, a == x {

**Comment by ajm188** [comment]
Hi @steve21124 good question. Undebt can work on any language. It is a find-and-replace tool based on a grammar which you define (in python) and then run on your desired input (in any language).

**Comment by steve21124** [comment]
Thank you for the quick response. do you have some tips to get started to solve one example issues above?

**Comment by evhub** [comment]
@steve21124 I would suggest looking through the various [`examples`](http://undebt.readthedocs.io/en/latest/examples.html) provided with Undebt. They should give you an idea of how to write pattern files.

**Comment by evhub** [comment]
@steve21124 In #28 @ajm188 just added an implementation of the pattern you're looking for in the examples packaged with Undebt. You can take a look here: <https://github.com/Yelp/undebt/blob/master/undebt/examples/swift.py>
