### ISSUE TITLE
Dry run option

### ISSUE THREAD

**Issue by seemethere** [Yelp/undebt#3]
Is there an option to not have it write in place?

If I just want to dry run this application without actually changing anything is that possible?

**Comment by ajm188** [comment]
There is not currently a dry run option, but one way to "fudge" would be to commit the files you want to run it on before running undebt. Then you can jump between both versions.

**Comment by seemethere** [comment]
Would you be opposed if I added one?

**Comment by evhub** [comment]
@seemethere In addition to using `git` like @ajm188 suggested, If you pipe input to `undebt` over `stdin`, it will write the output to `stdout`. Thus, you could do
```
cat ./test_file.txt | undebt -p ./some_pattern.py
```
to just print the modified file instead of actually changing it in-place.

**Comment by evhub** [comment]
@seemethere That being said, I wouldn't at all be opposed to adding an actual dry run option, if that's something you wanted to try to do.

**Comment by ajm188** [comment]
@seemethere of course you're welcome to submit a PR :)
