### ISSUE TITLE
Should the assert_keys argument to tokens_as_dict check for subset?

### ISSUE THREAD

**Issue by ajm188** [Yelp/undebt#4]
Consider the following grammar:

```python
grammar = (
     Optional(Keyword("mymodule") + DOT.suppress())("module")
     + condense(NAME + ZeroOrMore(DOT + ~Keyword("foo") + NAME))("classname")
     + DOT.suppress()
     + Keyword("foo")("method")
     + LPAREN.suppress()
     + NAME("arg")
     + RPAREN.suppress()
)
```

I would like to use the `assert_keys` argument to `tokens_as_list` to verify that `classname`, `method` and `arg` are all present, but since it checks for strict set equality, this will fail when the pattern captured by `module` appears in the input.

Should we check that the list of keys provided is a subset of the actual keys instead?

**Comment by evhub** [comment]
@ajm188 Use `assert_keys_in` instead of `assert_keys`!

See:

- example of `assert_keys_in`: <https://github.com/Yelp/undebt/blob/master/undebt/examples/contextlib_nested.py#L37>
- code for `assert_keys_in`: <https://github.com/Yelp/undebt/blob/master/undebt/pattern/util.py#L80>

**Comment by evhub** [comment]
Actually, wait, I think I acted too fast--you want the _opposite_ of what `assert_keys_in` does. You want to check that the provided keys are a subset of the actual keys, not that the actual keys are a subset of the provided keys.

**Comment by ajm188** [comment]
Yeah, so if I `assert_keys=[foo, bar]` then it should only raise an exception if either `foo` or `bar` does not appear in the keyset, but as long as both are there then anything else is fine as well.

**Comment by evhub** [comment]
@ajm188 Makes sense now! Sorry, at first I thought you were saying the opposite of that. Should just be a one-line change, and I think it's definitely a good one. I can just go ahead and do that right now.
