### ISSUE TITLE
Remove support for path-like module names

### ISSUE THREAD

**Issue by evhub** [Yelp/undebt#46]
In #41, Undebt was changed to only support importing pattern modules in `sys.path`, and to support writing those module names either how they would be imported, or as if they are a path. I propose removing the support for path-like module names, since the fact that they look like paths seems to imply that any path is valid, when in fact that's not the case.

This is especially true in the context of the README, which is now outdated and, most importantly, the example in which will _no longer work_, since it says to pass the path to the pattern file you create instead of installing it as a module and passing the module name.

**Comment by evhub** [comment]
Quoting my previous comment:

> Honestly, if we're only allowing modules that are on sys.path, I'm not sure why we're allowing path-like inputs in the first place. I would just enforce only something that can directly be passed to importlib.import_module (or __import__, which is functionally equivalent but stylistically discouraged).

**Comment by evhub** [comment]
I fixed the readme with https://github.com/Yelp/undebt/commit/580a97adfb59d5253d881db857a1bc4e4349f387, but the issue of removing support for path-like module names stands.

**Comment by asottile** [comment]
Sounds good to me. Modules++

**Comment by ajm188** [comment]
Closed by #54
