### ISSUE TITLE
Replace deprecated `<>` operator with `!=`

### ISSUE THREAD

**Issue by lwm** [Yelp/undebt#49]
Related to #21. 

I'll create an issue as I go, to make it more visible which ones I are finished.

Ref: [Avoid deprecated <> operator](https://www.quantifiedcode.com/knowledge-base/maintainability/Avoid%20deprecated%20%60%3C%3E%60%20operator/348m67d2)

**Comment by ajm188** [comment]
lol what. how old is that operator? I've literally never seen in python code. But sure, good to have in a library of patterns.

**Comment by lwm** [comment]
> lol what. how old is that operator?

hahaha. I had to fire up an interpreter to prove it existed to myself.

An easy first start ..

**Comment by evhub** [comment]
@ajm188 @lwm You can get in Python 3 also if you do `from __future__ import barry_as_FLUFL` (`barry_as_FLUFL` was an april fools joke by the Python dev team).

**Comment by ajm188** [comment]
This is starting to detract from the discussion, but I can't help myself. My favorite joke from the dev team is `from __future__ import braces`
