### ISSUE TITLE
Create a submodule under undebt.pattern for languages?

### ISSUE THREAD

**Issue by ajm188** [Yelp/undebt#51]
Theoretically, we will one day have common patterns for a variety of languages. Rather than littering `undebt.pattern` with {python, ruby, java, ...} modules, why don't we create a module called `undebt.pattern.lang` to house all of the patterns for the various languages?

Unfortunately, `undebt/pattern/python.py` will have to be moved there as well, which means all of the code that uses it will have to be updated. But, it's probably easier to do this now rather than in the future.

**Comment by evhub** [comment]
You could always make `undebt/pattern/python.py` just contain `from undebt.pattern.lang.python import *` if you wanted to make the change while still preserving backwards compatibility.

**Comment by ajm188** [comment]
I think I'll just nuke it. Because then we should also have a `undebt/pattern/ruby.py` file that contains `from undebt.pattern.lang.ruby import *` and so on, which defeats the entire purpose.

Do you think the general idea (about the submodule) is good, though?

**Comment by evhub** [comment]
@ajm188 Yes, I think it'd definitely be a good reorganization.

**Comment by ajm188** [comment]
Closed by #52
