### ISSUE TITLE
`_file_processor` no longer needs to be an object

### ISSUE THREAD

**Issue by ajm188** [Yelp/undebt#53]
Since we removed multiprocessing support, the file processor thingy doesn't actually need to be pickleable, so it doesn't have to be an object.

Perhaps there is a better way to structure this part of the code now?

**Comment by evhub** [comment]
+1 for making it a function now instead

**Comment by ajm188** [comment]
I am actively working on this, should have an initial PR soon.

We should talk about maybe revising the test suite, since this refactoring has me questioning the value of some of these tests 😛
