### ISSUE TITLE
readthedocs is out of date

### ISSUE THREAD

**Issue by ajm188** [Yelp/undebt#56]
it still shows that `undebt.pattern.python` is a thing, and has no reference to the new `undebt.pattern.lang` module or its submodules.

**Comment by evhub** [comment]
@ajm188 Just triggered a manual build and it looks like that fixed it. ReadTheDocs is supposed to automatically rebuild whenever you push to master, but for some reason it hasn't been doing that. I propose we keep this issue open for figuring out how to fix the automation, although the immediate issue of bringing it up-to-date is now fixed.

**Comment by ajm188** [comment]
@evhub sweet thanks. that's what I was hoping this issue would be for.

**Comment by ajm188** [comment]
It seems like I can't look at the repository settings... is it possible we're missing a webhook in the settings?

**Comment by evhub** [comment]
@ajm188 Yeah, that seems likely, although I also can't look at the settings, so I have no idea.

**Comment by ajm188** [comment]
@tomelm ^^

**Comment by tomelm** [comment]
<img width="179" alt="screen shot 2016-09-12 at 4 45 51 pm" src="https://cloud.githubusercontent.com/assets/153050/18456752/534f79ca-7908-11e6-9eab-651d273c9c13.png">

Enabled the webhook! Should be all set now.

**Comment by ajm188** [comment]
Awesome! Thanks @tomelm :)

Closing.
