### ISSUE TITLE
Add a helper function to match exactly N repititions of a pattern

### ISSUE THREAD

**Issue by ajm188** [Yelp/undebt#59]
This could be a useful addition to our collection of helpers.

Something like:
```python
def sequence(g, n):
    return reduce(lambda x, y: x + y, [g] * n)
```

@evhub thoughts?

**Comment by evhub** [comment]
@ajm188 I would suggest
```
import itertools, operator
def sequence(g, n):
    return itertools.reduce(operator.add, [g] * n)
```
but otherwise I like the idea.

**Comment by ajm188** [comment]
@evhub++ I always forget about `operator`

**Comment by ajm188** [comment]
also it's `functools` that has `reduce` not `itertools`

**Comment by evhub** [comment]
@ajm188++

**Comment by ajm188** [comment]
@evhub want to give me a review on #61 ? :)
