### ISSUE TITLE
pypi distfile does not include tests

### ISSUE THREAD

**Issue by 0-wiz-0** [Yelp/undebt#7]
The pypi distfile does not include the tests. Please add them.

**Comment by asottile** [comment]
What value-add is there here?  Even if they're included in the distribution they aren't executable (and setting up `setup.py test` requires eggs and easyinstall and sadness).

The supported workflow for running the tests is cloning this repository and using `tox`

**Comment by evhub** [comment]
@0-wiz-0 I agree with @asottile in that I don't really see the point of this. If you want to run the tests, just clone the repo and `make test`.

**Comment by 0-wiz-0** [comment]
I agree that for randomuser, the workflow you suggest is fine.
However, for packagers, it's good to have some self-tests included in a tarball distributed for packaging, so that trust in a new version can easily be established.

**Comment by asottile** [comment]
Packagers are going to look at (and probably contribute to) the source git repo anyway.  The github url is linked on pypi and the README covers continuous integration as well as coverage and the repository contains checked in tests.  Adding complexity to our packaging for zero value add seems not the best idea.

**Comment by evhub** [comment]
Closing as `won't fix`.
